spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: invite-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tcc
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port: 9600

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

amazonProperties:
  endpointUrl: https://s3.sa-east-1.amazonaws.com
  accessKey: AKIAZV6ZBNTXQXPTJWIE
  secretKey: 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
  bucketName: tcc-douglas-lucas

fabric:
  admin:
    username: admin
    password: adminpw
  ca:
    org1:
      url: http://localhost:7054
  orderer:
    url: grpc://localhost:7050
    name: orderer.example.com
  channel:
    name: mychannel
  org1:
    name: org1
    msp: Org1MSP
    peer0:
      name: peer0.org1.example.com
      url: grpc://localhost:7051
    peer1:
      name: peer1.org1.example.com
      url: grpc://localhost:8051
    peer2:
      name: peer2.org1.example.com
      url: grpc://localhost:9051
    peer3:
      name: peer3.org1.example.com
      url: grpc://localhost:10051
  userDirectoryPath: src/main/resources/user