server:
  port: 9600

spring:
  application:
    name: invite-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tcc
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka