server:
  port: 9800
  ssl:
    enabled: true
    keyStoreType: PKCS12
    keyStore: keystore.p12
    keyStorePassword: password
    keyAlias: bootifulsecurity
    clientAuth: want

spring:
  application:
    name: logs-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tcc
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    secureVirtualHostName: ${spring.application.name}
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka
