spring:
  application:
    name: document-service
  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 15MB

server:
  port: 8400

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

amazonProperties:
  endpointUrl: https://s3.sa-east-1.amazonaws.com
  accessKey: AKIAZV6ZBNTXQXPTJWIE
  secretKey: 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
  bucketName: tcc-douglas-lucas