server:
  port: 8763
  ssl:
    keyStoreType: PKCS12
    keyStore: classpath:keystore.p12
    keyStorePassword: password
    keyAlias: tomcat

spring:
  application:
    name: gateway
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB

security:
  requireSsl: true

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}/

#zuul.prefix=/api

# Disable accessing services using service name (i.e. gallery-service).
# They should be only accessed through the path defined below.

# Map paths to services
zuul:
  ignoredServices: '*'
  routes:
    imageService:
      path: /image-service/**
      serviceId: image-service
    videoService:
      path: /video-service/**
      serviceId: video-service
    documentService:
      path: /document-service/**
      serviceId: document-service
    credentialService:
      path: /credential-service/**
      serviceId: credential-service
    authService:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 122000

ribbon:
  ReadTimeout: 60000

niws:
  loadbalancer:
    availabilityFilteringRule:
      activeConnectionsLimit: 2147483647