server:
  port: 8763
  ssl:
    keyStoreType: PKCS12
    keyStore: classpath:keystore.p12
    keyStorePassword: password
    keyAlias: tomcat

spring:
  application:
    name: gateway

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tcc
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB

security:
  requireSsl: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: http://localhost:${server.port}/info
    healthCheckUrl: http://localhost:${server.port}/health
    homePageUrl: http://localhost:${server.port}/

#zuul.prefix=/api

# Disable accessing services using .service name (i.e. gallery-.service).
# They should be only accessed through the path defined below.

# Map paths to services
zuul:
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ignoredServices: '*'
  routes:
    imageService:
      path: /image-service/**
      serviceId: image-service
    videoService:
      path: /video-service/**
      serviceId: video-service
    documentService:
      path: /document-service/**
      serviceId: document-service
    credentialService:
      path: /credential-service/**
      serviceId: credential-service
    messageService:
      path: /message-service/**
      serviceId: message-service
    logsService:
      path: /logs-service/**
      serviceId: logs-service
    inviteService:
      path: /invite-service/**
      serviceId: invite-service
    notificationService:
      path: /notification-service/**
      serviceId: notification-service
    userService:
      path: /user-service/**
      serviceId: user-service
    authService:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie

Access-Control-Allow-Origin: '*'
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,DELETE,PATCH
Access-Control-Allow-Headers: Authorization,Access-Control-Allow-Origin,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range
Access-Control-Expose-Headers: X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 122000

ribbon:
  ReadTimeout: 60000

niws:
  loadbalancer:
    availabilityFilteringRule:
      activeConnectionsLimit: 2147483647